### ISSUE TITLE
Deploy to GitHub Pages failed

### ISSUE THREAD

**Issue by g4brielvs** [worldbank/iQual#2]
Hi @addypy! Thank you **so** much for accepting PR #1. It seems, however, that the `gh-pages`may be protected and the [workflow is failing](https://github.com/worldbank/iQual/actions/runs/4388241330/jobs/7684500688). Would you consider checking the [branch protection rules](https://github.com/worldbank/iQual/settings/branches) in case you would like to take advantage of this approach?

**Comment by addypy** [comment]
Hi @g4brielvs Thank you for looking into this. I've checked the branch protection rules, and only the main branch is protected.  
I think the issue was that `GITHUB_TOKEN` only had Read only permissions in [Workflow permissions settings](https://github.com/worldbank/iQual/settings/actions)
